### PR TITLE
Added config.yml with proper syntax

### PR DESCRIPTION
**Pull request by Passionatecricketer**
Syntax required for configure.yml corrected

### CODE REVIEW

**Review by bhavin192 — CHANGES_REQUESTED** [review]
Please revert the changes you made to `app.py` and `requirement.txt`

**Comment by bhavin192** [comment]
This fixes #8

**Comment by Passionatecricketer** [comment]
Changes to app.py and requirement.txt reverted

**Review by bhavin192 — APPROVED** [review]

**Comment by bhavin192** [comment]
@Passionatecricketer Thank you.

**Pull request merged**
